### ISSUE TITLE
remove index.js from .gitignore

### ISSUE THREAD

**Issue by queckezz** [rangle/basscss-radium#1]
Might wanna remove [.gitignore#L37](https://github.com/rangle/basscss-radium/blob/b0db1fb6a490edfc6bffd92039e5c00262407bbd/.gitignore#L37) so it commits your code :) Currently there is no `index.js`.

**Comment by bertrandk** [comment]
:sweat_smile: It was on purpose.

Since it's generated, I wanted to avoid committing an updated version whenever a change occurred. A little less noisy and error-prone. `npm i basscss-radium` should run the `prepublish` hook which in turn should run `make build`.

I'm not particularly against committing it though (can probably have a .git hook do it for me). Do you have a use-case in mind where committing index.js would help?

**Comment by queckezz** [comment]
Oh man im sorry for this, I didn't really look into it, how exactly it was implemented. I thought you implemented it by hand and not generated.

Sorry for the noise!

**Comment by bertrandk** [comment]
:smile: Ah, no worries. Thanks for taking the time.
